### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by RaT0M** [multiply-org/prior-engine#14]
@TonioF minor idea..or enhancement:
 could you add the webhooks for _ReadTheDocs_ in the `prior-engine` repo? I have auto-generated the documentation, but until the hooks at the repo are set, it does not update correctly..

**Comment by TonioF** [comment]
Good idea. I have some password trouble with ReadTheDocs right now, but as soon as this is sorted out, I will set the webhooks.

**Comment by TonioF** [comment]
Okay, done!
