### ISSUE TITLE
Logging / printing

### ISSUE THREAD

**Issue by RaT0M** [multiply-org/prior-engine#28]
As referenced in #21:

I did set up logging in the prior engine to avoid print statements and let us (later the user?) decide, how much (Level, e.g. debug, info, error, ..) information should be printed on screen and in a log file.

Maybe @TonioF can comment on this. What do you think of the approach of an file based logger configuration and per submodule loading of the `prior_logger` as class instance? (I actually did not really test it yet).

**Comment by TonioF** [comment]
I very much like thes logging, especially when compared to the print commands. What is implemented in prior_engine looks good to me.

What do you mean by your second paragraph? Do you have something more planned?

**Comment by TonioF** [comment]
Ah, after reading #21 I understand a bit better :) . Still, the current approach seems fine to me and I don't really see the need to extend this.

**Comment by RaT0M** [comment]
Ok, good.
