### ISSUE TITLE
ROI description in config

### ISSUE THREAD

**Issue by RaT0M** [multiply-org/prior-engine#4]
At the moment the ROI in mentioned in the sample config as `POLYGON ( (0, 0), (0,1 )) #blabla`.
Is this a 'convention' I don't know and if so how is it meant to be loaded? with _shapely_ module? gdal? so far this is not clear to me (for the moment parsing the string..)

--> How will the the coordinates finally be given? Has there been a decision yet?

**Comment by RaT0M** [comment]
it should be WKT conform..but isn't?
then loading via `shapely.wkt` or `ogr.CreateGeometryFromWkt` would be viable.
maybe already answered the question.

**Comment by TonioF** [comment]
Hi, yes, all descriptions of spatial data shall be in WKT format. The ROI in the sample config is dummy code and probably it became too dumb. shapely is a good choice. I'm in favor of using that.
