### ISSUE TITLE
Interface prior-engine OUTPUT

### ISSUE THREAD

**Issue by RaT0M** [multiply-org/prior-engine#8]
How should the prior data be passed on to the `inference-engine`?

A secondary question to this is, if the MULTIPLY platform will have a central way/module of resampling input/intermediate(prior)/output data (see [issue in multiply-core](https://github.com/multiply-org/multiply-core/issues/6))

Passing on prior data as NetCDF files would be beneficial, as the resampling would be very easy. But, read/write operations should be limited.
@JorisTimmermans mentioned that there is an **in-memory netcdf-file-container** format which could be used.

What are your thoughts on this @jgomezdans and @TonioF?

**Comment by jgomezdans** [comment]
Two cases:

1. For spatially distributed variables (e.g. soil moisture) where we just get a mean vector and a diagonal covariance matrix, something similar to one multiband raster file (bands for  each timestep) and one multiband raster file with the variances  (same band scheme as mean). At any case, rasters ought to be working with GDAL.

2. For vegetation parameters, where you expect to get some sort of covariance structure mapped to e.g. LC class, a "look up" raster and then a set of means per class (CSV file), and a set of class covariance matrices (CSV files). 

A third case would be the direct use of dynamical models, but these would be interfaced directly through the inference engine, and is not what we're looking to do right now.

**Comment by RaT0M** [comment]
for now has been defined in coding workshop. also referenced in [KaFKA issue #4](https://github.com/multiply-org/KaFKA-InferenceEngine/issues/4).
